### ISSUE TITLE
BACKEND: Admin Roles

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#302]
Kim would like 3 types of admin roles (super admin, admin, staff admin) for her site, so that she can make changes as needed.

Acceptance Criteria:
[] Create a super admin that is capable of adding/removing other admins and doing everything all admins are able to do.
[] Create an admin that can add resources, modify text, upload videos and photos and make other changes to the website, but does not have any other privilege.
[] Create a staff admin that can communicate with volunteers, sponsors, enrollees and others.  Only staff admin are able to access and view information (google forms information) pertaining to these people.  Staff admin does not have any other privilege.

**Comment by dkaplan88** [comment]
When you pick up this story, FIRST come up with a Plan of Action of how you are going to go about completing this story including details about the Backend Architecture. 

Then present that Plan to a Tech Lead (either in person or Slack if we are not in)

Do this before you write any code for this story

**Comment by dkaplan88** [comment]
https://docs.djangoproject.com/en/2.2/topics/auth/default/

**Comment by JavaOfDoom** [comment]
**When picking up this ticket please read through this!**

Run `docker-compose up`
To login to the Django admin page go to `localhost:8000/admin/`
Use `kim.wright@example.com` for the user and `password` for the password. "Kim Wright" is the test super user.
When you are stopping docker-compose use `Ctrl + C` to stop it and keep the test users. If you run `docker-compose down` you will lose all test user information.

Test user information can be changed from the admin page or from the create_test_users.py file in the backend.

Here are the links to the Django Admin documentation. (https://docs.djangoproject.com/en/3.0/ref/contrib/admin/) (https://docs.djangoproject.com/en/3.0/ref/contrib/admin/actions/)
I was not able to determine an exact direction for the admin page. With the Django Admin page you can set a _superuser_ and _staff_ permission which would be good for the _super admin_ and _admin_ roles that the client would like. The _staff admin_ role does not need to be handled by Django Admin but would probably be best handled by G-Suite since we are using google docs for much of the communication.

Feel free to reach out to me for any further questions you might have!
All the best and I'll see you at the launch party!
Joe
