### ISSUE TITLE
BACKEND: Enrollee Email Notification

### ISSUE THREAD

**Issue by hmichele** [the-difference-engine/ymim#329]
As a potential enrollee, I would like an email notification confirming my application has been accepted, so that I am aware of my status in the program.

Acceptance Criteria:
[] Send an email to enrollees that have been accepted into the program.

**Comment by khanh-do** [comment]
@hmichele I would like to ask for clarification on this story. If an email notification is to be sent to the enrollee after they are accepted into the program, is this task separate from this platform? For example, after the enrollee submits their information, the client reviews and then approves their entry into the program. The next step would be that the client sends an email to the enrollee. This last step would be separate from this platform, correct?

**Comment by hmichele** [comment]
@khanh-do Yes, the step for the enrollee notification is separate from the platform.

**Comment by khanh-do** [comment]
Please find information below regarding my POC work done for this feature thus far. I had set up Google sheets and scripts in the Enroll form for our client to be able to send email notifications to potential enrollees directly from Google sheets. I provided as many comments as I could in the code for clarification.

I learned how to work the scripts starting with this tutorial:
https://developers.google.com/apps-script/articles/sending_emails

Then I followed this video to add a custom tab in the Enroll sheets menu bar from which the client could run the script without leaving the sheets page. And how to create a custom template for the email.
https://www.youtube.com/watch?v=EvQC1N9JMs0

Finally, I followed Google documentation for personalizing emails:
https://developers.google.com/apps-script/articles/mail_merge#section_3_exercise_modifying_the_form_and_the_personalized_email

Summary of features:
On the Enroll sheet, I renamed the first sheet to "Enroll Applicants". Naming the sheet is important in order to identify the sheet (used in the code). I added columns H and I to this sheet. (Columns could be moved to the right if needed - as long as we adjust the script accordingly). The client can indicate in Column H if the applicant is accepted or not. I set up the code to send emails only to rows where this column contains a "Yes". Column I contains a flag to indicate if an email has been sent. I set up the code to not send emails to rows where this column already contains an "EMAIL_SENT" flag.

![Screenshot from 2019-12-28 23-35-40](https://user-images.githubusercontent.com/29875882/71552926-31deb400-29cb-11ea-810a-d6fb241dce15.png)


I added another sheet, which I named "Acceptance". This sheet contains a preliminary email template for our client to customize. I added a Subject line and an Email message, both of which can be modified as needed. The client should be notified not to change the placement of the cells. The code takes the data from the cells to format the emails. The client may change the text if she desires, just not the positions of the cells and the string interpolation stuff (${"Name"}). Additional features may be added here as needed (see the Google tutorial listed above for more information).

![Screenshot from 2019-12-28 23-04-50](https://user-images.githubusercontent.com/29875882/71552932-4d49bf00-29cb-11ea-8c1b-a28921e3e0a5.png)


Demonstration:
Before (inbox):

![Screenshot from 2019-12-28 23-07-07](https://user-images.githubusercontent.com/29875882/71552651-e5917500-29c6-11ea-8377-e0f9f606e5fb.png)

Client goes to Enroll sheets. She adds "Yes" to Column H in the rows 2 and 3 and "No" to row 4, the Not Accepted person. Notice that the first row already has been flagged "EMAIL_SENT", so no emails will be sent to Sonia. The client clicks on the custom tag in the menu bar that I had created "Email Notification", then clicks on "Send Emails".

![Screenshot from 2019-12-28 23-08-51](https://user-images.githubusercontent.com/29875882/71552711-75372380-29c7-11ea-8979-d2bf1af9c90d.png)

The code will go through each row of entries, and send emails only to those labelled "Yes" and not labelled "EMAIL_SENT". The code has now flagged rows 2 and 3 as EMAIL_SENT. The fourth row was not sent an email because of the "No" flag. See below.

![Screenshot from 2019-12-28 23-15-47](https://user-images.githubusercontent.com/29875882/71552737-0a3a1c80-29c8-11ea-88a0-bfb5cc22aa30.png)

After (inbox):
In our inbox, we have received the personalized emails as expected (rows 2 and 3 of sheets) with the customized subject line and email template:

![Screenshot from 2019-12-28 23-19-51](https://user-images.githubusercontent.com/29875882/71552783-a2d09c80-29c8-11ea-8cee-5df6a17645b7.png)

The emails for rows 2 and 3 are shown below. Further styling may be added as desired. Notice the recipient's name for each email is personalized with respect to the name listed on the sheets.

![Screenshot from 2019-12-28 23-23-47](https://user-images.githubusercontent.com/29875882/71552807-27bbb600-29c9-11ea-8911-8f4e4641d96b.png)

![Screenshot from 2019-12-28 23-25-43](https://user-images.githubusercontent.com/29875882/71552823-67829d80-29c9-11ea-8342-687f6da6690c.png)

Clicking on SendEmails again should result in no new emails being sent because of the flags have been set up automatically.

**Comment by khanh-do** [comment]
To access the code: 
Go to Enroll form. 
Click on Responses. 
Click on symbol for "View responses in Sheets". It is the icon to the left of the 3 button menu. This will open sheets in a new tab.
On sheets, select "Tools" "<>Script Editor"

The code after line 88 was taken from the tutorial. It wasn't used but I thought to include them in case someone wants to use it.

Note: More features could be added as desired (for example, a rejection email template). And possibly a feature to lock the code so no one can inadvertently corrupt the code.
