### ISSUE TITLE
Documentation: Contact-Us - Google Form

### ISSUE THREAD

**Issue by JigSays** [the-difference-engine/ymim#424]
As an Admin, I would like to be able to known how to access and update the Google Form on the 'Contact-Us' page of the site. 

![Screenshot 2020-02-20 20.01.21.png](https://images.zenhubusercontent.com/5a7202374b5806bc2bc51343/17ebc2fc-b5e1-4b5e-be47-4b3cfbbcf062)

Acceptance Criteria:

- [ ] Admin needs to know how to access the hosted area of the Google Form

- [ ] Admin needs to know how to make changes to the Google Form

- [ ] Admin needs to know how to access the date once the Google Form is submitted

- [ ] Admin needs to know how to change the notification settings for the Google Form

- [ ] Admin needs to know for to change the delivery method of the notifications for the Google Form

- [ ] Admin needs to know the credentials needed to access the Google Form account. 
[] Screenshots and step by step instructions need to be included.

**Comment by hmichele** [comment]
@iquinterom 

Please see below:

The documentation needs to pertain to the Enrollment form, but I'm seeing things on the screenshot that aren't for the form.

- Please provide examples on how to edit questions on form. The documentation only shows the edit screen, but no instructions.

- **Page 5, step 1** - Please fix the typo for icon. 
- **Page 7, step 5** - Missing an arrow to indicate icon.
- **Page 8, step 6 c-e** - make sure it is noted that those are examples only not on enroll form.
- **Page 10, 6f** screenshot
- **Page 27, step 2** -
- **Page 35, step 5** - downloads folder
- **Page 36, step 3** is not a step. Please make it a note instead of a step.
- **Page 36, step 4** - Add a screenshot with an arrow.
