### ISSUE TITLE
Documentation: Enrollment - Google Form

### ISSUE THREAD

**Issue by JigSays** [the-difference-engine/ymim#426]
As an Admin, I would like to be able to known how to access and update the Google Form on the 'Enrollment' page of the site. 

![Screenshot 2020-02-20 20.13.22.png](https://images.zenhubusercontent.com/5a7202374b5806bc2bc51343/8ea9cc39-b115-4bee-be7c-e3de8bb8d533)

Acceptance Criteria:

- [ ] Admin needs to know how to access the hosted area of the Google Form

- [ ] Admin needs to know how to make changes to the Google Form

- [ ] Admin needs to know how to access the data once the Google Form is submitted

- [ ] Admin needs to know how to change the notification settings for the Google Form

- [ ] Admin needs to know for to change the delivery method of the notifications for the Google Form

- [ ] Admin needs to know the credentials to access the Google Form account. 
[] Screenshots and step by step instructions need to be included.

**Comment by hmichele** [comment]
@iquinterom 

Please see below:

The documentation needs to pertain to the Enrollment form, but I'm seeing things on the screenshot that aren't for the form.

**Page 4, 14-16** -  the "last name" field is shown on both screenshots. Why is it there?  It is not on the form.  Please correct form and documentation.

**Page 6, step 5, step 6 c-e** - I'm assuming these screenshots are used as an example since this field does not exist on the Enrollment form.  If so, please make sure it is noted that those are examples only, so there is not confusion for the client.

**Page 8, 6f** - Please use the correct screenshot that pertains to Enrollment.
 
**Accessing the Data of your Forms, Accessing the Data in a Spreadsheet, Set-up Notifications and Saving data** - Only show screenshots that are for the Enrollment form, not Volunteer.  Please check throughout the doc for that as well.
