### ISSUE TITLE
Documentation: Enrollment - Email Notification | Acceptance

### ISSUE THREAD

**Issue by JigSays** [the-difference-engine/ymim#427]
As an Admin, once a user submits a form on "Enrollment", I want to be able to know how to inform them whether they are accepted or denied into the program, how to change the language in the email notifications, and how to change the email address from which the emails are generated. 

![Screenshot 2020-02-20 20.13.22.png](https://images.zenhubusercontent.com/5a7202374b5806bc2bc51343/e1d5a283-07f5-4ab2-8f1c-5cec98845b64)

Acceptance Criteria:

- [ ] Admin has the knowledge to access the location where the "Enrollment" form data is saved.

- [ ] Admin has knowledge to of how to select a record that has been submitted thru the "Enrollment" page form and choose whether to "accept" or "reject" the application.

- [ ] Admin has the knowledge of how to change the language in the email for the acceptance email.

- [ ] Admin has the knowledge of how to change the language in the email for the rejection email.

- [ ] Admin has the knowledge of how to change the email address that the acceptance | rejection emails are generated from.

- [ ] Admin is provided the credentials to access the email account generating the acceptance | rejection emails from the Enrollment Google Form. 
[] Screenshots and step by step instructions need to be included.

**Comment by hmichele** [comment]
@iquinterom 
Please check the doc for the (1) note Jordan made.  

My comments are below:

- Please change the title at the of the top of the documentation to "Enrollment Acceptance/Rejection Email Notification Documentation".

- Move credentials for login and password to page 2 instead of page 3, so it's shown before the login instructions.

- Provide only one way to access Google drive.

- Note that there are 3 types of tabs (enroll, acceptance, rejection) in the Enroll spreadsheet as you have it and section those out.  Explain what an acceptance and rejection email is.

- Leave "Send email notification", "Adding collaborators" and "Accessing script code" sectioned out, but  remove other sections not noted here.

- Referencing "Accessing script code" should only include information related to fields in the spreadsheet when needing to add/remove fields.  Remove anything else.  Note at the top of this section that changes here are not recommended and will affect email notifications from working.  The layout provided needs to remain the same in order for it to work.  User must be very careful in any changes made.

- Remove page 43, iii, page 44, all steps on page 45.  

- Remove everything on only page 47 except v. 

- Ensure numbering is correct.
