### ISSUE TITLE
About Page - Design

### ISSUE THREAD

**Issue by Auprodmgrdf** [the-difference-engine/ymim#99]
***********SEE COMMENTS BELOW FOR NEW CHANGES.****************

Note that social media icons will match the landing page color, scheme, and design. Utilizing the style guide available in the Webstyle Epic, create design for About Page according to mockup below.![about page-min.png](https://images.zenhubusercontent.com/5c5ce522ebd8ee7342dd6d78/6f20f19b-31ae-4018-a1b3-994af2b7263f)

**Comment by chitownhope** [comment]
@Tduncan14 and @dkaplan88 this ticket is being returned to In Progress because it does not meet all design requirements.  In particular, the sub-headings:  Our Mission, Our Values and Our Approach to Engagement.

Pulling @AimeeCasden into this ticket to finish and close this one out. 

Thanks.

**Comment by Tduncan14** [comment]
Yeah,  I just added the layout/structure and the singleCarousel component has not been added to it. Alex was  working on it last before he left.We had finally received the pictures and he told me he will update it.
It’s a lot more components that needs to be updated.it was just pushed into staging to have work close as possible to the mock up so we can have more production to show Kimberly when she arrived.    On Thursday, August 15, 2019, 7:30:52 PM CDT, tina r <notifications@github.com> wrote:  
 
 
@Tduncan14 and @dkaplan88 this ticket is being returned to In Progress because it does not meet all design requirements. In particular, the sub-headings: Our Mission, Our Values and Our Approach to Engagement.

Pulling @AimeeCasden into this ticket to finish and close this one out.

Thanks.

**Comment by Tduncan14** [comment]
i guess he forgot to push

**Comment by Tduncan14** [comment]
No he completed it. He showed me and Dan i believe because he did great job on it.

**Comment by AimeeCasden** [comment]
so do I need to do anything with this still or no?

**Comment by dkaplan88** [comment]
Since tree was assigned to this im going to move it back but can we get a bit more clearer requirements for this @chitownhope @hmichele

**Comment by hmichele** [comment]
Everything looks ok thus far except the sizing of the photos under "Our People".  Kim would like the photos to be reduced in size.

Acceptance criteria:

[] Change the height and width of the photos to 400 px. 
[] Adjust the text next to the photos accordingly so it aligns well with the page.

**Comment by hmichele** [comment]
Please make the following changes:

Realign Kim's photo so that it is vertically centered with the text to the right of her photo.

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/eecfc682-6ea2-48fa-828f-06f99038eda8)

Create a thin, grey border around each of the photos:

![image.png](https://images.zenhubusercontent.com/5d5607f1409ffe1c45065249/8a57ba75-0412-412d-8f4c-d88126dea046)
